name: "Deploy Backend"
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.fronchik.com
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: registry.fronchik.com/mesto-api:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull registry.fronchik.com/mesto-api:latest
            cd /home/${{ secrets.USER }}/fronchik
            docker-compose down mesto-api
            docker-compose up -d mesto-api
